### ISSUE TITLE
求论文

### ISSUE THREAD

**Issue by done520** [FPPGroup/CodonBERT#1]
您好，请问这项研究有公开论文吗？期待阅读

**Comment by renzilin** [comment]
> 您好，请问这项研究有公开论文吗？期待阅读

您好，该工作接收之后我们将给您发链接

**Comment by done520** [comment]
"CodonBert: a BERT-based architecture tailored for codon optimization using the cross-attention mechanism"这是正在发表中的论文题目吧？

**Comment by renzilin** [comment]
> "CodonBert: a BERT-based architecture tailored for codon optimization using the cross-attention mechanism"这是正在发表中的论文题目吧？

是的

**Comment by done520** [comment]
@renzilin 我对您这项研究非常感兴趣，方便微信交流吗？

**Comment by renzilin** [comment]
> @renzilin 我对您这项研究非常感兴趣，方便微信交流吗？

Hi there, the article is available: 
https://doi.org/10.1093/bioinformatics/btae330
