### ISSUE TITLE
data_formatting.py is empty？

### ISSUE THREAD

**Issue by shenweiyan** [FPPGroup/CodonBERT#3]
I noticed that [data_formatting.py](https://github.com/FPPGroup/CodonBERT/blob/main/scripts/data_formatting.py) is an empty file. Is this intentional? Thank you.

**Comment by renzilin** [comment]
> I noticed that [data_formatting.py](https://github.com/FPPGroup/CodonBERT/blob/main/scripts/data_formatting.py) is an empty file. Is this intentional? Thank you.

You can use the [fasta_to_npy.py](https://github.com/FPPGroup/CodonBERT/blob/main/scripts/fasta_to_npy.py) to generate the numpy file from FASTA inputs. Data_formatting.py should be the file that was uploaded incorrectly. We'll correct it soon.
