### ISSUE TITLE
Request to add a license for CodonBERT

### ISSUE THREAD

**Issue by Cauch-BS** [FPPGroup/CodonBERT#4]
I hope this message finds you well. I have been exploring CodonBERT and I want to commend you on the great work being done on this project. 

However, currently It is unclear to me if academic use of this code is permitted, as the repository currently does not include a license. It is generally perceived that software that doesn’t have a license means users have no permission from to use, modify, or share the software. 

Adding a license to the project would greatly benefit both users and contributors by providing clear guidelines on the usage rights and obligations associated with the code. This helps in maintaining transparency and ensuring that the code can be used and shared appropriately.

Could you please consider adding a license to the repository? 

Thank you for your time and consideration. I look forward to your response.

**Comment by renzilin** [comment]
Really appreciate for your suggestion
